#=========================================================#
#====                                                     #
#==                         #01                           #
#                      Initialization                     #
#                                                       ==#
#                                                     ====#
#=========================================================#
/control/maximumStoredHistory 1000
/control/saveHistory ./Documents/MacroHistory.dat

#=========================================================#
#====                                                     #
#==                         #02                           #
#                        Verbosity                        #
#                                                       ==#
#                                                     ====#
#=========================================================#
/control/verbose 0
/run/verbose 0
/run/particle/verbose 0
/event/verbose 0
/tracking/verbose -1
/process/verbose 0
/process/eLoss/verbose 0
/process/em/verbose 0
#/process/had/particle_hp/verbose 0
/material/verbose 0

/SKG4/Verbose 0
/SKG4/ErrorVerbose/Primary 0
/SKG4/ErrorVerbose/Run 0
/SKG4/ErrorVerbose/Event 0
/SKG4/ErrorVerbose/Track 0
/SKG4/ErrorVerbose/Step 0
/SKG4/ErrorVerbose/Stack 0
/SKG4/ErrorVerbose/Physics 0
/SKG4/ErrorVerbose/Construct 0

#=========================================================#
#====                                                     #
#==                         #03                           #
#                          Global                         #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Global/LowEGainRun 81586
/SKG4/Global/Run 999999
/SKG4/Global/Subrun 1
/SKG4/Global/PhysicsType 0
/SKG4/Global/Geometry 5



#=========================================================#
#====                                                     #
#==                         #04                           #
#                         Physics                         #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Physics/Verbose 0
#/SKG4/Physics/SetPhysicsEM local2
/SKG4/Physics/SetPhysicsEM emlivermore
/SKG4/Physics/SetPhysicsOptical local
/SKG4/Physics/SetPhysicsDecay on
/SKG4/Physics/SetPhysicsStopping on
/SKG4/Physics/SetPhysicsExtraEM on
/SKG4/Physics/SetPhysicsHadronElastic HP
/SKG4/Physics/SetPhysicsHadronInelastic local_w/_annrigd
/SKG4/Physics/SetPhysicsIonElastic on
/SKG4/Physics/SetPhysicsIonInelastic QMD


#=========================================================#
#====                                                     #
#==                         #05                           #
#                     Material Property                   #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Detector/Material/WaterProperty  ./dat_file/MaterialProperty/Latest/WaterProperty.dat
/SKG4/Detector/Material/AcrylProperty  ./dat_file/MaterialProperty/Latest/AcrylProperty3.dat
/SKG4/Detector/Material/VacuumProperty  ./dat_file/MaterialProperty/Latest/VacuumProperty.dat
/SKG4/Detector/Material/AirProperty  ./dat_file/MaterialProperty/Latest/AirProperty.dat
/SKG4/Detector/Material/GdHydrate 8
/SKG4/Detector/Material/GdConcentration 0.0
/SKG4/Detector/Material/WaterTransparencyRun 81588
#/SKG4/Detector/Material/IDTBAParameter RUNNUM
/SKG4/Detector/Material/IDTBAParameter 0.
/SKG4/Detector/Material/WaterParameter 201908


#=========================================================#
#====                                                     #
#==                         #06                           #
#                       PMT Property                      #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Detector/ID/PMTData ./dat_file/PMT/pmtmap_20190617.dat
/SKG4/Detector/ID/PMTQEData ./dat_file/PMT/QETable.dat
#/SKG4/Detector/ID/PMTMaterialTable ./dat_file/PMT/PMTMaterialTable.dat
# before QEtune
#/SKG4/Detector/ID/CorrectionFactor 0.88312522

# after QEtune
#/SKG4/Detector/ID/CorrectionFactor 0.8848418131

# after new QEtune
#/SKG4/Detector/ID/CorrectionFactor 0.8587529
/SKG4/Detector/ID/CorrectionFactor 0.863989413

/SKG4/Detector/ID/PMTQETableVersion 5_1

#/SKG4/OD/Digitize false
#/SKG4/OD/EffRatio 1.
#/SKG4/OD/ADSCThr 0.25
#/SKG4/OD/ADSThrF 0.01
#/SKG4/OD/DSAntT0 4000.



#=========================================================#
#====                                                     #
#==                         #07                           #
#                   Detector Construction                 #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Detector/CheckOverlap false
/SKG4/Calibration/CalibMode LINAC
/SKG4/Calibration/LINAC/SetRun 81588
/SKG4/Detector/Update


#=========================================================#
#====                                                     #
#==                         #08                           #
#                        Dark Noise                       #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/DarkNoise/Mode 2
/SKG4/DarkNoise/Run 81586


#=========================================================#
#====                                                     #
#==                         #09                           #
#                     Software Trigger                    #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/SWTRG/Apply true
/SKG4/SWTRG/InGateOnly true
/SKG4/SWTRG/TriggerMask -1 
/SKG4/SWTRG/TimeOffset 0


#=========================================================#
#====                                                     #
#==                         #10                           #
#                        ROOT File                        #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/RootFile/TTree/Information true
/SKG4/RootFile/TTree/Cerenkov true
/SKG4/RootFile/TTree/PMT true
/SKG4/RootFile/TTree/Incident true
/SKG4/RootFile/TTree/Secondary false
/SKG4/RootFile/Name /disk02/lowe8/mharada/test.root


#=========================================================#
#====                                                     #
#==                         #11                           #
#                     Primary Generator                   #
#                                                       ==#
#                                                     ====#
#=========================================================#
/run/initialize
#/process/optical/cerenkov/setMaxPhotons 25


/SKG4/Primary/ParticleType Calib


#=========================================================#
#====                                                     #
#==                        #12                            #
#                      NEUT Settings                      #
#          ( Must be set after /run/initialize )          #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4NeutCascadeInterfaceCommand/xsecMomentumRange 0 0.5
/SKG4NeutCascadeInterfaceCommand/addValidElement O
/SKG4NeutCascadeInterfaceCommand/addValidElement H


#=========================================================#
#====                                                     #
#==                         #13                           #
#                         Beam On                         #
#                                                       ==#
#                                                     ====#
#=========================================================#
/SKG4/Global/Reload
/run/beamOn 1000
